# Generated by Django 3.1.2 on 2020-10-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octavius', '0002_auto_20201022_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='sleep',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='wakeup',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
