# Generated by Django 3.1.2 on 2020-10-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octavius', '0003_auto_20201023_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='sleep',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='wakeup',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
